### ISSUE TITLE
Not Working with tensorflow 2.3.0 

### ISSUE THREAD

**Issue by TaylorHere** [lspvic/jupyter_tensorboard#68]
~~~shell
    Traceback (most recent call last):
│      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
│        result = method(*self.path_args, **self.path_kwargs)
│      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 3178, in wrapper
│        return method(self, *args, **kwargs)
│      File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
│        .new_instance(data["logdir"], reload_interval=reload_interval)
│      File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance
│        purge_orphaned_data=purge_orphaned_data)
│      File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 47, in create_tb_app
│        tensorboard.assets_zip_provider)
│      File "/opt/conda/lib/python3.7/site-packages/tensorboard/backend/application.py", line 147, in standard_tensorboard_wsgi
│        if reload_interval >= 0:
│      File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 165, in TensorBoardWSGIApp_2x
│        window_title=flags.window_title)
│    TypeError: __init__() got an unexpected keyword argument 'db_connection_provider'
~~~

**Comment by cliffwoolley** [comment]
See https://github.com/lspvic/jupyter_tensorboard/pull/63
